### ISSUE TITLE
how to find memory adress?

### ISSUE THREAD

**Issue by yungd1plomat** [LloydLabs/Windows-API-Hashing#1]
How can i find memory adress of winapi?

**Comment by LloydLabs** [comment]
Normally, after the library that contains the API is loaded, e.g. `ntdll.dll` through a `LoadLibrary(..)` call, you can pass the `HANDLE` of the library to `GetProcAddress` with the API name. However, this code replicates that. On this line, https://github.com/LloydLabs/Windows-API-Hashing/blob/master/resolve.c#L116, you can see the structure member `lpAddr` is set to the relative address of the API in memory - ready for use by your program.
